// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xanhpdnbtxawkauheghr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbmhwZG5idHhhd2thdWhlZ2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMjYzNzEsImV4cCI6MjA3NzYwMjM3MX0.vXIwWEn4Q-p3HUQMjpxETm2-ECI-aJtI1GjufNSkW4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);