// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wosgnznicmrynvqbkpfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvc2duem5pY21yeW52cWJrcGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTg0MjYsImV4cCI6MjA3Nzc3NDQyNn0.lIR44fPhbJYnEjE7jf5pGmkxXHOjIuoMthX26uCpylE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);